---
- hosts: localhost
  collections:
    - theforeman.foreman
  gather_facts: false
  vars_files:
    - vars/server.yml
  roles:
    - role: content_rhel
      vars:
        foreman_manifest_download: false
        foreman_manifest_path: "/path/to/your/downloaded/manifest.zip"
        foreman_content_rhel_enable_rhel7: false
        foreman_content_rhel_enable_rhel8: true
        foreman_content_rhel_sync_now: true
        foreman_content_rhel_wait_for_syncs: false
